const events = [
  {
    id: 1,
    title: "Concerto Villastellone",
    date: "13 Settembre 2025",
    month: "Settembre",
    year: "2025",
    location: "Villastellone",
    description: "Concerto in occasione del raduno provincia di Torino.",
    image: "hero-image.avif",
    type: "Concerto",
    startTime: "21:00",
    endTime: "23:00",
    locandina: "locandina-villastellone.jpg",
  },
  {
    id: 2,
    title: "Raduno Provinciale",
    date: "14 Settembre 2025",
    month: "Settembre",
    year: "2025",
    location: "Villastellone",
    description: "Raduno provincia di Torino.",
    image: "sfilata.avif",
    type: "Raduno",
    startTime: "09:00",
    endTime: "16:00",
    locandina: "locandina-villastellone.jpg",
  },
  {
    id: 3,
    title: "Musica, Fanfare e Caroselli",
    date: "25 Ottobre 2025",
    month: "Ottobre",
    year: "2025",
    location: "Pala200, Via Santa Cristina 5, Settimo Torinese",
    description: "30° anniversario rifondazione fanfara di Settimo Torinese.",
    image: "carosello.avif",
    type: "Serata musicale",
    startTime: "21:00",
    endTime: null,
  },
  {
    id: 4,
    title: "30° anniversario rifondazione Fanfara e festa sezionale",
    date: "26 Ottobre 2025",
    month: "Ottobre",
    year: "2025",
    location: "Settimo Torinese",
    description: "Sfilata per le vie della città di Settimo Torinese.",
    image: "sfilata2.avif",
    type: "Sfilata",
    startTime: "09:30",
    endTime: "17:00",
  },
];

export default events;
