import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../fontello-bersaglieri/css/fontello.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Analytics } from "@vercel/analytics/next";
import CookieBanner from "@/components/CookieBanner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bersaglieri Settimo Torinese",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden max-w-screen`}
      >
        <Header />
        {children}
        <Analytics />
        <Footer />
        <CookieBanner />
      </body>
    </html>
  );
}
